Feature/10 grundstruktur fuer die entwicklung eines eigenen qgis plugins für die visualisierung unterschiedlicher datensaetze
vitrum-connect/5gla-qgis pull request #13
Opened 2024-04-30 10:24 UTC by Vitrum-LL

2024-04-30 10:27 UTC, Vitrum-LL commented
@saschadoemer Das Problem mit den signierten commits lies sich nachträglich leider nicht mehr beheben.  E-Mail und Github User passten nicht zusammen. Habe einen neuen Branch ohne mit richtiger Namenskonvention und nun verifizierten commits.

2024-05-02 06:05 UTC, saschadoemer requested changes

2024-05-02 06:05 UTC, saschadoemer commented on .idea/.gitignore
Bitte keine Projektdateien der IDE einchecken, d.h. `.idea` raus und in die globale `.gitignore`

2024-05-02 06:05 UTC, saschadoemer commented on Textdokument (neu).txt
Ich denke, die gehört hier nicht hin, oder?

2024-05-02 06:05 UTC, saschadoemer commented on .idea/.gitignore
Das führt dazu, dass ein Öffnen in der anderen IDE automatisch Konflikte aufwirft.

![image](https://github.com/vitrum-connect/5gla-qgis/assets/1309344/00d823e0-7636-4790-b40e-2c9567f700fb)

2024-05-02 06:21 UTC, closed without merging