Feature/10 grundstruktur fuer die entwicklung eines eigenen qgis plugins fuer die visualisierung unterschiedlicher datensaetze
vitrum-connect/5gla-qgis pull request #14
Opened 2024-05-02 06:26 UTC by Vitrum-LL

@saschadoemer Ist angepasst. War auch noch ein ü im Branchname das hab ich auch noch gefixed

2024-05-02 07:39 UTC, saschadoemer requested changes

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +This QGIS plugin provides the visualization of data from the 5gLA platform. It is part of the 5GLa project, which is funded by the German Federal Ministry of Transport and Digital Infrastructure ( BM
```suggestion
This QGIS plugin provides the visualization of data from the 5gLA platform. It is part of the 5GLa project, which is funded by the German Federal Ministry of Transport and Digital Infrastructure (BMVI). The website of the project is https://www.5gla.de/, you can find all additional information there.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +If you want to create you own QGIS Plugin you can follow along. If you just want to use the plugin you can start straight with the Section "Install the plugin".
```suggestion
If you want to create your own QGIS Plugin, you can follow along. If you just want to use the plugin, you can start straight with the Section "Install the plugin".
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +For the creation of the QGIS plugin we use the Plugin Builder 3 which itself is a QGIS plugin. The Plugin can be installed directly over the QGIS UI.
```suggestion
For the creation of the QGIS plugin, we use the Plugin Builder 3, which itself is a QGIS plugin. The Plugin can be installed directly over the QGIS UI.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +The "Class name" must be an allowed name for a python class. The "Module name" must be an allowd name for python module.
```suggestion
The "Class name" must be an allowed name for a python class. The "Module name" must be an allowed name for python module.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +Extra components couldb be added but currently they are not necessary.
```suggestion
Extra components could be added, but currently they are not necessary.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +The URLs to the github repo, the 5GLa Website and our author contact details will be added.
```suggestion
The URLs to the GirtHub repository, the 5GLa Website and our author contact details will be added.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +Before we can install the plugin we need to compile the plugin. To change the icon later, it is necessary to recompile the plugin. The icon will be stored in the resources.py. To compile the plugin w
```suggestion
Before we can install the plugin, we need to compile the plugin. To change the icon later, it is necessary to recompile the plugin. The icon will be stored in the resources.py. To compile the plugin, we use the OSGeo4W shell, which comes with the QGIS installation. 
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +We cd into the plugin folder and use the pyrcc5 comand to compile the plugin.
```suggestion
We navigate into the plugin folder and use the `pyrcc5` comand to compile the plugin.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +First we need to copy our plugin folder (fivegla_visualization) to the Qgis python plugin directory.
```suggestion
First, we need to copy our plugin folder `fivegla_visualization` to the QGIS python plugin directory.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +The Folder will be initialized with the start of qgis so you to restart qgis after you copying the folder to the plugin directory.
```suggestion
The Folder will be initialized with the start of qgis so you to restart qgis after you copy the folder to the plugin directory.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +The easiest way is to go to settings --> Userprofiles --> open current profile directory. In the explorer you cd to /python/plugins. Copy the plugin folder to this directory.
```suggestion
The easiest way is to go to settings --> Userprofiles --> open current profile directory. In the explorer you navigate to /python/plugins. Copy the plugin folder to this directory.
```

2024-05-02 07:39 UTC, saschadoemer commented on README.md
> +You should find the fivegla_visualization in the UI. If you check the checkbox left to the plugin you install it. if you uncheck it you deactivate it. By clicking Uninstall plugin on the bottom you r
```suggestion
You should find the fivegla_visualization plugin in the UI. If you check the checkbox left to the plugin, you install it. If you uncheck it, you deactivate it. By clicking "Uninstall plugin" on the bottom, you remove / delete the whole plugin folder from your plugins directory.
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/__init__.py
>  /***************************************************************************
Persönliche Meinung, diese Kommentare sind Clutter und auf Dauer wirklich hart zu pflegen. Ich würde darauf verzichten wollen und die Repos einheitlich halten. D.h. den ganzen Block raus (gilt für alle Dateien).

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/__init__.py
>      #
```suggestion
    
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +class DatabaseConnection:
Kommentare für die Methoden und Klasse ergänzen.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +            return False
Das ist schwierig und schluckt die Exceptions. Mindestanforderung sollte hier schon sein, dass die geloggt wird. Sonst ist das Debugging später echt hart.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +    def addPostgisLayer(self, table_name, geometryColumn):
```suggestion
    def add_postgis_layer(self, table_name, geometry_column):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +        if self.uri == None:
```suggestion
        if self.uri is None:
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +            print("Layer failed to load!")
Normales `print` würde ich durch einen Logger ersetzen, gibt sonst auf Dauer Problem und könnte nicht so leicht in eine Datei umgeroutet werden.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
>          # Save reference to the QGIS interface
Kommentare im Code würde ich mir sparen, die Aktionen sind ja anhand der Befehle ersichtlich. Wo das nicht der Fall ist --> Methoden einführen.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
>      # noinspection PyMethodMayBeStatic
Kann man natürlich so machen, oder einfach `static` machen :D

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
>      def initGui(self):
```suggestion
    def init_gui(self):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
> +        """Add Settings Action"""
Das ist eigentlich ein reservierter Kommentar für Methoden. Soll der da stehen, was ich nicht denke, dann müsste er mit einer # starten.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
> +    def firstStart(self):
```suggestion
    def first_start(self):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/fivegla_visualization.py
> +    """This methode will ensure that all dependencys are setup before the first dialog is called"""
Als Methodenkommentar falsch platziert.

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/metadata.txt
> +about=This plugin visualizes the measured values ​​and results of the 5GLa project. This includes, among other things, the measured values ​​from soil moisture sensors and multispectral drone images.
```suggestion
about=This plugin visualizes the measured values ​​and results of the 5GLa project. This includes, among other things, the measured values ​​from soil moisture sensors and multi-spectral drone images.
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/metadata.txt
> +about=This plugin visualizes the measured values ​​and results of the 5GLa project. This includes, among other things, the measured values ​​from soil moisture sensors and multispectral drone images.
Sieht so aus, als ob sich da unsichtbare Zeichen eingeschlichen haben:

![image](https://github.com/vitrum-connect/5gla-qgis/assets/1309344/a8c0c641-d8ee-47fc-af29-f6cfb99ab19c)

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings.py
> +    def __init__(self, iface, callbackFirstStart):
```suggestion
    def __init__(self, iface, call_back_first_start):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings.py
> +    def loadCredentials(self):
```suggestion
    def load_credentials(self):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings.py
> +    def saveCredentials(self):
```suggestion
    def save_credentials(self):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings.py
> +    def testConnection(self):
```suggestion
    def test_cionnection(self):
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings.py
> +        if isConnected:
```suggestion
        if is_connected:
```

2024-05-02 07:39 UTC, saschadoemer commented on fivegla_visualization/settings/fivegla_visualization_settings_dialog.py
> +class fivegla_visualization_settingsDialog(QtWidgets.QDialog, FORM_CLASS):
Das passt vom Naming her irgendwie gar nicht.

2024-05-02 12:28 UTC, BSO-Lukas commented
@saschadoemer magst du nochmal rüber gucken? Ich meine ich habe alles umgesetzt.

2024-05-03 06:18 UTC, saschadoemer approved these changes

2024-05-03 06:18 UTC, merged