Feature/7 visualisierung der empfangenen gps positionen in qgis zur moeglichen echtzeit darstellung der flugroute der drohne
vitrum-connect/5gla-qgis pull request #15
Opened 2024-05-07 15:00 UTC by Vitrum-LL

2024-05-08 09:25 UTC, saschadoemer requested changes
Kleinere Sachen haben direkt gefixt, bitte die Kommentare einmal durchschauen.

2024-05-08 09:25 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
>          except Exception as e:
`e` kann raus, wird eh nicht genutzt. Entweder loggen, meine Präferenz, oder aus dem Block nehmen. Sonst wird die Exception geschluckt.

2024-05-08 09:25 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +        except Exception as e:
Das Gleiche an dieser Stelle, entweder die Exception loggen oder aufploppen lassen. Grundsatz sollte immer sein - Log or Throw.

2024-05-08 09:25 UTC, saschadoemer commented on fivegla_visualization/database_manager/device_position_gateway.py
> +            return None
Das sorgt dafür, dass du zwei Fälle hast in denen du `None` als Rückgabewert ohne Log hast. D.h. bei der fehlenden Connection oder andernfalls bei fehlender ID.

2024-05-08 10:34 UTC, Vitrum-LL commented
@saschadoemer Müsste nun passen. Hatte mir deine commits angesehen. Deine Konvention ist imports alphabetisch sortieren? Dann mach ich das zukünftig so.

2024-05-08 11:08 UTC, saschadoemer commented
Standeinstellung von PyCharm 👌🏻

2024-05-13 06:32 UTC, saschadoemer approved these changes

2024-05-13 06:33 UTC, merged