filtering sensor data according to date range - warnings revised
vitrum-connect/5gla-qgis pull request #20
Opened 2024-08-09 07:54 UTC by BSO-Jannis

added date-boxes for filtering accordinga defined time period

warnings revised --> displayed in the foreground

2024-08-09 08:18 UTC, saschadoemer requested changes
@BSO-Jannis bitte die `pycache` Ordner aus dem PR entfernen. Danach schaue ich weiter drauf.

2024-08-09 11:22 UTC, saschadoemer requested changes
Bitte auch die anderen Ordner entfernen 😀

![image](https://github.com/user-attachments/assets/fa5415d7-abbe-4ac3-a8b5-c11bdbcb4de3)

2024-08-12 07:50 UTC, saschadoemer requested changes

2024-08-12 07:50 UTC, saschadoemer commented on fivegla_visualization/database_manager/database_connection.py
> +            self.custom_logger.log_info(query)
Level INFO ist für die reine Query zu viel, hier würde ich auf DEBUG oder auf TRACE loggen.

2024-08-12 07:50 UTC, saschadoemer commented on fivegla_visualization/database_manager/soil_moisture_sensor_gateway.py
> +        end_string = '2024-08-03T00:00:00.000Z'
Hart verdrahtete Datumsangaben?

2024-08-12 07:50 UTC, saschadoemer commented on fivegla_visualization/device_measurement/fivegla_visualization_device_measurement.py
> +        start_date_string = start_date_time.toString("yyyy-MM-ddTHH:mm:ss.zzzZ")
Format generisch auslagern, sodass das mehrfach genutzt werden kann.

2024-08-12 07:50 UTC, saschadoemer commented on fivegla_visualization/device_measurement/fivegla_visualization_device_measurement.py
> +        end_date_string = end_date_time.toString("yyyy-MM-ddTHH:mm:ss.zzzZ")
Das Verwenden von Typen in Variablennamen sollte nach Clean Code vermieden werden, da es weniger Chancen für das Refactoring bietet.

2024-08-13 07:49 UTC, BSO-Jannis commented
- debug logging level integrated 
- renaming variables according to clean-code-agreements
- outsourcing convert datetime --> date-strings functionality

2024-08-13 20:04 UTC, saschadoemer requested changes
Sorry, leider nein. Du hast immer noch die gecachten Dateien drin.

![image](https://github.com/user-attachments/assets/f382968d-047f-4dfa-87a0-9f2d6d24fd92)

Lass uns gemeinsam draufschauen, damit die rauskommen.

2024-08-14 14:51 UTC, BSO-Jannis commented
- integration of load_config() method
- method loads data from config file
- within the config file is the timedelta (today - 14 days previously)

2024-08-14 18:42 UTC, saschadoemer approved these changes

2024-08-14 18:42 UTC, saschadoemer commented on fivegla_visualization/device_measurement/fivegla_visualization_device_measurement.py
> +            two_weeks_ago = date.today() - timedelta(days=14)
Keine `magic numbers`, auslagern in die Konfiguration oder wenigstens als Konstante außerhalb des Codes.

2024-08-14 18:43 UTC, merged